# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file and install dependencies
COPY src/naive/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the Python script
COPY src/naive/main.py .

# The command to run when the container starts
ENTRYPOINT ["python", "main.py"]
